server:
  port: 8761

spring:
  config:
    import: vault://secret/discovery-service
  cloud:
    vault:
      host: vault
      port: 8200
      scheme: http
      token: root
      kv:
        enabled: true
  application:
    name: discovery-service
